### ISSUE TITLE
Meaning of GitHub Online?

### ISSUE THREAD

**Issue by gcapes** [hoytpr/git_beginner#2]
Just wondering what is meant by this term? Perhaps 'user fork' or 'your fork' of a SWC repo might be clearer?

**Comment by hoytpr** [comment]
Hi @gcapes, and thanks.  I'll read through to see if it needs to be changed. This is really for people unfamiliar or confused with GitHub and I'm keeping it really simple. The emphasis is on the (made-up) "GIT Triangle" and is emphasizing the distinguishment between what is "yours" locally, and what is "yours" online.  GitHub online does mean "Your repositories on GiitHub" and could correctly be called your fork of a SWC repo. In some ways this is just my interpretation of the confusion I've experienced, and may not be representative of everyone. The ultimate goal is to have a clearly defined and ridiculously simplistic "protocol" that a beginning contributor can follow until they are more comfortable.
